# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T02:04:15+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, RootModel


class NotificationCategorySubscription(Enum):
    NOTIFICATION_CATEGORY_UNSPECIFIED = 'NOTIFICATION_CATEGORY_UNSPECIFIED'
    ALL = 'ALL'
    SUSPENSION = 'SUSPENSION'
    SECURITY = 'SECURITY'
    TECHNICAL = 'TECHNICAL'
    BILLING = 'BILLING'
    LEGAL = 'LEGAL'
    PRODUCT_UPDATES = 'PRODUCT_UPDATES'
    TECHNICAL_INCIDENTS = 'TECHNICAL_INCIDENTS'


class ValidationState(Enum):
    VALIDATION_STATE_UNSPECIFIED = 'VALIDATION_STATE_UNSPECIFIED'
    VALID = 'VALID'
    INVALID = 'INVALID'


class GoogleCloudEssentialcontactsV1Contact(BaseModel):
    email: Optional[str] = Field(
        None,
        description='Required. The email address to send notifications to. The email address does not need to be a Google Account.',
    )
    languageTag: Optional[str] = Field(
        None,
        description='Required. The preferred language for notifications, as a ISO 639-1 language code. See [Supported languages](https://cloud.google.com/resource-manager/docs/managing-notification-contacts#supported-languages) for a list of supported languages.',
    )
    name: Optional[str] = Field(
        None,
        description='Output only. The identifier for the contact. Format: {resource_type}/{resource_id}/contacts/{contact_id}',
    )
    notificationCategorySubscriptions: Optional[
        List[NotificationCategorySubscription]
    ] = Field(
        None,
        description='Required. The categories of notifications that the contact will receive communications for.',
    )
    validateTime: Optional[str] = Field(
        None,
        description='The last time the validation_state was updated, either manually or automatically. A contact is considered stale if its validation state was updated more than 1 year ago.',
    )
    validationState: Optional[ValidationState] = Field(
        None,
        description='The validity of the contact. A contact is considered valid if it is the correct recipient for notifications for a particular resource.',
    )


class GoogleCloudEssentialcontactsV1ListContactsResponse(BaseModel):
    contacts: Optional[List[GoogleCloudEssentialcontactsV1Contact]] = Field(
        None, description='The contacts for the specified resource.'
    )
    nextPageToken: Optional[str] = Field(
        None,
        description='If there are more results than those appearing in this response, then `next_page_token` is included. To get the next set of results, call this method again using the value of `next_page_token` as `page_token` and the rest of the parameters the same as the original request.',
    )


class NotificationCategory(Enum):
    NOTIFICATION_CATEGORY_UNSPECIFIED = 'NOTIFICATION_CATEGORY_UNSPECIFIED'
    ALL = 'ALL'
    SUSPENSION = 'SUSPENSION'
    SECURITY = 'SECURITY'
    TECHNICAL = 'TECHNICAL'
    BILLING = 'BILLING'
    LEGAL = 'LEGAL'
    PRODUCT_UPDATES = 'PRODUCT_UPDATES'
    TECHNICAL_INCIDENTS = 'TECHNICAL_INCIDENTS'


class GoogleCloudEssentialcontactsV1SendTestMessageRequest(BaseModel):
    contacts: Optional[List[str]] = Field(
        None,
        description='Required. The list of names of the contacts to send a test message to. Format: organizations/{organization_id}/contacts/{contact_id}, folders/{folder_id}/contacts/{contact_id} or projects/{project_id}/contacts/{contact_id}',
    )
    notificationCategory: Optional[NotificationCategory] = Field(
        None,
        description='Required. The notification category to send the test message for. All contacts must be subscribed to this category.',
    )


class GoogleProtobufEmpty(BaseModel):
    pass


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class NotificationCategories(RootModel[List[NotificationCategory]]):
    root: List[NotificationCategory]


class GoogleCloudEssentialcontactsV1ComputeContactsResponse(BaseModel):
    contacts: Optional[List[GoogleCloudEssentialcontactsV1Contact]] = Field(
        None,
        description='All contacts for the resource that are subscribed to the specified notification categories, including contacts inherited from any parent resources.',
    )
    nextPageToken: Optional[str] = Field(
        None,
        description='If there are more results than those appearing in this response, then `next_page_token` is included. To get the next set of results, call this method again using the value of `next_page_token` as `page_token` and the rest of the parameters the same as the original request.',
    )
